;** ###################################################################
;**     This code is generated by the Device Initialization Tool.
;**     It is overwritten during code generation.
;**     USER MODIFICATION ARE PRESERVED ONLY INSIDE INTERRUPT SERVICE ROUTINES
;**     OR EXPLICITLY MARKED SECTIONS
;**
;**     Project     : DeviceInitialization
;**     Processor   : MC9S08QE8CLC
;**     Version     : Component 01.003, Driver 01.08, CPU db: 3.00.049
;**     Datasheet   : MC9S08QE8RM Rev. 3 1/2008
;**     Date/Time   : 2017-05-18, 09:26, # CodeGen: 1
;**     Abstract    :
;**         This module contains device initialization code 
;**         for selected on-chip peripherals.
;**     Contents    :
;**         Function "MCU_init" initializes selected peripherals
;**
;**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
;**     
;**     http      : www.freescale.com
;**     mail      : support@freescale.com
;** ###################################################################

; MODULE MCUinit

        INCLUDE MC9S08QE8.inc          ; I/O map for MC9S08QE8CLC

; User declarations and definitions
;   Code, declarations and definitions here will be preserved during code generation
; End of user declarations and definitions

CODE_SECT:      SECTION

        XDEF    MCU_init
;** ===================================================================
;**     Method      :  MCU_init (component MC9S08QE8_32)
;**
;**     Description :
;**         Device initialization code for selected peripherals.
;** ===================================================================
MCU_init:
  ; ### MC9S08QE8_32 "Cpu" init code ... 
  ; Common initialization of the write once registers 
        ; SOPT1: COPE=0,COPT=1,STOPE=0,BKGDPE=1,RSTPE=0 
        LDA     #$42
        STA     SOPT1                                               
        ; SPMSC1: LVDF=0,LVDACK=0,LVDIE=0,LVDRE=1,LVDSE=1,LVDE=1,BGBE=0 
        LDA     #$1C
        STA     SPMSC1                                               
        ; SPMSC2: LPR=0,LPRS=0,LPWUI=0,PPDF=0,PPDACK=0,PPDE=1,PPDC=0 
        LDA     #$02
        STA     SPMSC2                                               
        ; SPMSC3: LVWIE=0 
        LDA     SPMSC3
        AND     #$F7
        STA     SPMSC3
  ;  System clock initialization 
        ;Test if the device trim value is stored on the specified address
        LDA     $FFAF
        CBEQA   #$FF, SkipTrim
        ; ICSTRM: Initialize internal clock trim from a non volatile memory 
        LDA     $FFAF
        STA     ICSTRM
        ; ICSSC: Initialize internal clock trim from a non volatile memory 
        LDA     $FFAE
        AND     #$01
        STA     ICSSC
SkipTrim:
        ; ICSC1: CLKS=0,RDIV=0,IREFS=1,IRCLKEN=0,IREFSTEN=0 
        MOV     #$04,ICSC1             ; Initialization of the ICS control register 1 
        ; ICSC2: BDIV=1,RANGE=0,HGO=0,LP=0,EREFS=0,ERCLKEN=0,EREFSTEN=0 
        MOV     #$40,ICSC2             ; Initialization of the ICS control register 2 
while_Cpu0:                            ; Wait until the source of reference clock is internal clock 
        BRCLR   4,ICSSC,while_Cpu0
        ; Initialization of the ICS status and control
        ; ICSSC: DRST_DRS=0,DMX32=0 
        LDA     ICSSC
        AND     #$1F
        STA     ICSSC
whileVal_Cpu0:                         ; Wait until the FLL switches to Low range DCO mode 
        LDA     ICSSC
        AND     #$C0
        BNE     whileVal_Cpu0

        ; SCGC1: TPM2=1,TPM1=1,ADC=1,IIC=1,SCI=1 
        LDA     #$FF
        STA     SCGC1                                               
        ; SCGC2: DBG=1,FLS=1,IRQ=1,KBI=1,ACMP=1,RTC=1,SPI=1 
        LDA     #$FF
        STA     SCGC2                                               
  ; Common initialization of the CPU registers 
        ; PTADD: PTADD5=0 
        BCLR    $05,PTADD
        ; PTASE: PTASE7=0,PTASE6=0,PTASE4=0,PTASE3=0,PTASE2=0,PTASE1=0,PTASE0=0 
        LDA     PTASE
        AND     #$20
        STA     PTASE
        ; PTBSE: PTBSE7=0,PTBSE6=0,PTBSE5=0,PTBSE4=0,PTBSE3=0,PTBSE2=0,PTBSE1=0,PTBSE0=0 
        CLRA
        STA     PTBSE                                               
        ; PTCSE: PTCSE7=0,PTCSE6=0,PTCSE5=0,PTCSE4=0,PTCSE3=0,PTCSE2=0,PTCSE1=0,PTCSE0=0 
        CLRA
        STA     PTCSE                                               
        ; PTDSE: PTDSE3=0,PTDSE2=0,PTDSE1=0,PTDSE0=0 
        LDA     PTDSE
        AND     #$F0
        STA     PTDSE
        ; PTADS: PTADS7=0,PTADS6=0,PTADS5=0,PTADS4=0,PTADS3=0,PTADS2=0,PTADS1=0,PTADS0=0 
        CLRA
        STA     PTADS                                               
        ; PTBDS: PTBDS7=0,PTBDS6=0,PTBDS5=0,PTBDS4=0,PTBDS3=0,PTBDS2=0,PTBDS1=0,PTBDS0=0 
        CLRA
        STA     PTBDS                                               
        ; PTCDS: PTCDS7=0,PTCDS6=0,PTCDS5=0,PTCDS4=0,PTCDS3=0,PTCDS2=0,PTCDS1=0,PTCDS0=0 
        CLRA
        STA     PTCDS                                               
        ; PTDDS: PTDDS3=0,PTDDS2=0,PTDDS1=0,PTDDS0=0 
        CLRA
        STA     PTDDS                                               
  ; ### Init_IRQ init code 
  ; ** Initialize pin PTA5_IRQ_TCLK_RESET ** 
        ; Disable IRQ Interrupt
        ; IRQSC: IRQIE=0 
        BCLR    $01,IRQSC
        ; IRQSC: IRQPE=1 
        BSET    $04,IRQSC
        ; IRQSC: IRQACK=1 
        BSET    $02,IRQSC
        ; Enable IRQ Interrupt
        ; IRQSC: IRQIE=1 
        BSET    $01,IRQSC
  ; ### 
        CLI                            ; Enable interrupts 

        RTS


;** ===================================================================
;**     Interrupt handler : isrVlvd
;**
;**     Description :
;**         User interrupt service routine. 
;**     Parameters  : None
;**     Returns     : Nothing
;** ===================================================================
        XDEF    isrVlvd
isrVlvd:

        RTI
; end of isrVlvd 


;** ===================================================================
;**     Interrupt handler : isrVirq
;**
;**     Description :
;**         User interrupt service routine. 
;**     Parameters  : None
;**     Returns     : Nothing
;** ===================================================================
        XDEF    isrVirq
isrVirq:
   		
   		
		LDA		PTCD
   		EOR		#$FF
   		STA		PTCD
   		LDA		#$FF
AntiR	DBNZA	AntiR
   		LDA		#$FF
   		STA		$60
   		BSET	2,IRQSC
   		CLI
        RTI
; end of isrVirq 



; Initialization of the CPU registers in FLASH 
        ; NVPROT: FPS7=1,FPS6=1,FPS5=1,FPS4=1,FPS3=1,FPS2=1,FPS1=1,FPDIS=1 
        ORG     NVPROT
        DC.B    $FF
        ; NVOPT: KEYEN=0,FNORED=1,SEC01=1,SEC00=0 
        ORG     NVOPT
        DC.B    $7E



        XREF    _Startup

; Interrupt vector table 
  ifndef UNASSIGNED_ISR
UNASSIGNED_ISR: EQU     $FFFF          ; unassigned interrupt service routine
  endif

        ORG     $FFCE                  ; Interrupt vector table
_vect:
        DC.W    UNASSIGNED_ISR         ; Int.no. 24 Vrtc (at FFCE)                  Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no. 23 VReserved23 (at FFD0)           Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no. 22 VReserved22 (at FFD2)           Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no. 21 VReserved21 (at FFD4)           Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no. 20 Vacmpx (at FFD6)                Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no. 19 Vadc (at FFD8)                  Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no. 18 Vkeyboard (at FFDA)             Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no. 17 Viic (at FFDC)                  Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no. 16 Vscitx (at FFDE)                Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no. 15 Vscirx (at FFE0)                Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no. 14 Vscierr (at FFE2)               Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no. 13 Vspi (at FFE4)                  Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no. 12 VReserved12 (at FFE6)           Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no. 11 Vtpm2ovf (at FFE8)              Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no. 10 Vtpm2ch2 (at FFEA)              Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no.  9 Vtpm2ch1 (at FFEC)              Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no.  8 Vtpm2ch0 (at FFEE)              Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no.  7 Vtpm1ovf (at FFF0)              Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no.  6 Vtpm1ch2 (at FFF2)              Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no.  5 Vtpm1ch1 (at FFF4)              Unassigned
        DC.W    UNASSIGNED_ISR         ; Int.no.  4 Vtpm1ch0 (at FFF6)              Unassigned
        DC.W    isrVlvd                ; Int.no.  3 Vlvd (at FFF8)                  Used
        DC.W    isrVirq                ; Int.no.  2 Virq (at FFFA)                  Used
        DC.W    UNASSIGNED_ISR         ; Int.no.  1 Vswi (at FFFC)                  Unassigned
        DC.W    _Startup               ; Int.no.  0 Vreset (at FFFE)                Reset vector




        END     ; MODULE MCUinit

;** ###################################################################
;**
;**     This file was created by Processor Expert 10.0 [05.03]
;**     for the Freescale HCS08 series of microcontrollers.
;**
;** ###################################################################
